#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

MIGRATION="supabase/migrations/20260902000000_foundation.sql"

banner "NFC Prospection: Supabase + Netlify provisioning"

# ── 1. Create the Supabase project ────────────────────────────────────────
stage "Supabase: create the project"
say "One production project holds the whole deployment; there is no staging project."
open_url "https://supabase.com/dashboard/projects"
step "Click 'New project', name it 'nfc-prospection', pick the region closest to you."
step "Choose a strong database password and store it in your password manager."
step "Wait until the project finishes provisioning (about two minutes)."
pause "Project is up?"

# ── 2. Capture the API keys ───────────────────────────────────────────────
stage "Supabase: API keys"
say "The URL and anon key ship to the browser; the service-role key never does."
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Copy 'Project URL' (https://<ref>.supabase.co)."
ask SUPABASE_URL "Paste the project URL:"
step "Copy the 'anon public' key."
ask SUPABASE_ANON_KEY "Paste the anon key:"
step "Reveal and copy the 'service_role' key (local tooling and tests only)."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the service-role key:"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── 3. Apply the schema ───────────────────────────────────────────────────
stage "Supabase: apply the schema"
say "Creates places, visit_history, activity_log, settings and quota, their RLS"
say "policies, the (user_id, place_id) unique constraint and increment_quota()."
note "Migration file: $MIGRATION"
if command -v supabase >/dev/null 2>&1; then
  say "The Supabase CLI is installed, so you can push instead of pasting:"
  note "  supabase link --project-ref <ref> && supabase db push"
fi
open_url "https://supabase.com/dashboard/project/_/sql/new"
step "Open $MIGRATION, copy its full contents into the SQL editor."
step "Click 'Run'. It should finish with 'Success. No rows returned'."
pause "Schema applied?"

# ── 4. Create the single account ──────────────────────────────────────────
stage "Supabase: create the one account"
say "Exactly one account ever exists. Create it before signup is switched off."
open_url "https://supabase.com/dashboard/project/_/auth/users"
step "Click 'Add user' → 'Create new user'."
step "Enter the prospector's email and a strong password, tick 'Auto Confirm User'."
ask SUPABASE_TEST_EMAIL "Repeat the email you used:"
ask_secret SUPABASE_TEST_PASSWORD "Repeat the password (stored in .env for tests):"
write_env SUPABASE_TEST_EMAIL "$SUPABASE_TEST_EMAIL"
write_env SUPABASE_TEST_PASSWORD "$SUPABASE_TEST_PASSWORD"

# ── 5. Close public signup ────────────────────────────────────────────────
stage "Supabase: disable public signup"
warn "After this, no further account can be created from the app or the API."
if confirm "Have you signed in as that account at least once, or confirmed it exists?"; then
  open_url "https://supabase.com/dashboard/project/_/auth/providers"
  step "Open the 'Email' provider."
  step "Turn OFF 'Allow new users to sign up', then Save."
  step "Leave 'Confirm email' as-is; nobody else can reach signup now."
  pause "Public signup disabled?"
else
  SKIPPED+=("Disable public signup in Supabase Auth → Providers → Email")
  warn "skipped: create and verify the account first, then re-run this wizard"
fi

# ── 6. Link Netlify to the repository ─────────────────────────────────────
stage "Netlify: link the repository"
say "Netlify then redeploys the site automatically on every push to main."
open_url "https://app.netlify.com/start"
step "Choose 'Import an existing project' → GitHub → thomas-hinton/nfc-prospecting."
step "Leave the build settings alone: netlify.toml already sets the command"
step "  ('npm ci && npm run build') and the publish directory ('dist')."
step "Set the production branch to 'main', then deploy."
ask NETLIFY_SITE_URL "Paste the site URL Netlify gave you (https://....netlify.app):"
write_env NETLIFY_SITE_URL "$NETLIFY_SITE_URL"

# ── 7. Netlify environment variables and first real deploy ────────────────
stage "Netlify: environment variables"
say "scripts/build.mjs reads these at build time and writes them into dist/config.js."
open_url "https://app.netlify.com/sites/_/configuration/env"
step "Site configuration → Environment variables → 'Add a variable'."
step "Add SUPABASE_URL = $SUPABASE_URL"
step "Add SUPABASE_ANON_KEY = (the anon key from stage 2)."
warn "Never add SUPABASE_SERVICE_ROLE_KEY here: it would reach the browser."
step "Then Deploys → 'Trigger deploy' → 'Clear cache and deploy site'."
pause "Deploy finished?"
step "Open the site: it must show the login screen, and your credentials must work."
open_url "$NETLIFY_SITE_URL"
pause "Login works and the session survives a reload?"

finish
say "Run the integration tests against the real project with:"
note "  set -a && . ./.env && set +a && npx vitest run"
